### ISSUE TITLE
Part6. Part 4. 未完成

### ISSUE THREAD

**Issue by Joshua0128** [En-Huei/Code-Your-Stage_Remote-Assignment#1]
Part 4. 未完成
Part 6. 未完成

其他部分完成了
New Due Time : 9/18 23:59

---

一個需要釐清的點是這次的作業都是偏前端的內容，後端的部分我們已經寫好讓你們能夠透過 API 互動，作業完全沒有讓你實做後端 RESTFul API 的部分。
這也是現代前後端分離常見的協作方式，後端只要提供 API 的 interface 讓前端去 call 。 前端不用煩惱後端是怎麼處理資料，儲存資料。後端也不用擔心前端要怎麼呈現資料，只需要協調好 API 的就可以了。
在前端如何處理 API 的內容可以參考：https://teamtreehouse.com/library/asynchronous-programming-with-javascript 。
有遇到問題都歡迎在 DC 提問與討論～

**Comment by En-Huei** [comment]
Finished
