### ISSUE TITLE
有錯誤的import 

### ISSUE THREAD

**Issue by Joshua0128** [En-Huei/Code-Your-Stage_Remote-Assignment#2]
<img width="603" alt="image" src="https://github.com/En-Huei/Code-Your-Stage_Remote-Assignment/assets/14936390/e5f9ed5a-92b3-451f-b309-0754f170f8c9">

請盡快修正，並且於此issue回覆
Due Time : 9/19 23:59

**Comment by En-Huei** [comment]
Comment again lines of code in useSWRFetch.jsx that's originally commented, and no need to be used in the assignment.
(the time I uncommented the nookie module, I also ran "npm install nookie" to install it, although it's  not affecting the assignment features.
